// <auto-generated />
namespace LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Agent_NULLABLE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agent_NULLABLE));
        
        string IMigrationMetadata.Id
        {
            get { return "202402110357357_Agent_NULLABLE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
